import React from 'react';
import ReactMarkdown from 'react-markdown';
import { Download, ArrowLeft, Printer } from 'lucide-react';

interface SummaryViewProps {
  summary: string;
  onReset: () => void;
}

export const SummaryView: React.FC<SummaryViewProps> = ({ summary, onReset }) => {
  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="w-full max-w-4xl mx-auto p-6">
      {/* Header - Hidden when printing */}
      <div className="flex justify-between items-center mb-8 no-print">
        <button 
          onClick={onReset}
          className="flex items-center gap-2 text-gray-400 hover:text-white transition-colors"
        >
          <ArrowLeft className="w-5 h-5" />
          <span>Back to Recorder</span>
        </button>
        <div className="flex gap-4">
           <button
            onClick={handlePrint}
            className="flex items-center gap-2 px-6 py-2 bg-vet-600 hover:bg-vet-500 text-white rounded-lg font-medium transition-colors shadow-lg"
          >
            <Printer className="w-5 h-5" />
            <span>Print / Save PDF</span>
          </button>
        </div>
      </div>

      {/* Content Area - Designed for both Screen and Print */}
      <div className="bg-white text-gray-900 rounded-xl shadow-2xl overflow-hidden print:shadow-none print:rounded-none">
        {/* Print Header */}
        <div className="bg-vet-900 text-white p-8 print:bg-white print:text-black print:p-0 print:mb-6 print:border-b-2 print:border-black">
          <div className="flex justify-between items-start">
            <div>
              <h1 className="text-3xl font-bold mb-2">סיכום הרצאה וטרינרית</h1>
              <p className="opacity-80 print:opacity-100">LectureSense AI Analysis</p>
            </div>
            <div className="text-left text-sm opacity-60 print:opacity-100">
              <p>{new Date().toLocaleDateString('he-IL')}</p>
              <p>Generated by Gemini 3 Pro</p>
            </div>
          </div>
        </div>

        {/* Markdown Content */}
        <div className="p-8 print:p-0 text-lg leading-relaxed text-right" dir="rtl">
          <article className="prose prose-lg max-w-none prose-headings:text-vet-800 prose-p:text-gray-800 prose-strong:text-vet-900">
             <ReactMarkdown>{summary}</ReactMarkdown>
          </article>
        </div>
        
        {/* Footer */}
        <div className="bg-gray-50 p-6 text-center text-gray-500 text-sm print:hidden">
          Generated automatically by LectureSense. Verify all medical details with original source material.
        </div>
      </div>
    </div>
  );
};
